### ISSUE TITLE
LiteralFloat with value `Zero`  not supported in compilation of integral

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/ffcx#699]
MWE:
```python
import basix.ufl
import ufl

c_el = basix.ufl.element("Lagrange", "interval", 1, shape=(1,))
mesh = ufl.Mesh(c_el)
C = ufl.as_tensor([[0, 0], [0, 1]])

integrand = ufl.transpose(C)[0, 0]

dx = ufl.Measure("dx", domain=mesh)
J = integrand * dx
forms = [J]
```
Traceback
```bash
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/shared/ffcx/ffcx/__main__.py", line 14, in <module>
    sys.exit(main())
  File "/root/shared/ffcx/ffcx/main.py", line 75, in main
    code_h, code_c = compiler.compile_ufl_objects(
  File "/root/shared/ffcx/ffcx/compiler.py", line 118, in compile_ufl_objects
    code = generate_code(ir, options)
  File "/root/shared/ffcx/ffcx/codegeneration/codegeneration.py", line 48, in generate_code
    code_integrals = [integral_generator(integral_ir, options) for integral_ir in ir.integrals]
  File "/root/shared/ffcx/ffcx/codegeneration/codegeneration.py", line 48, in <listcomp>
    code_integrals = [integral_generator(integral_ir, options) for integral_ir in ir.integrals]
  File "/root/shared/ffcx/ffcx/codegeneration/C/integrals.py", line 42, in generator
    parts = ig.generate()
  File "/root/shared/ffcx/ffcx/codegeneration/integral_generator.py", line 168, in generate
    all_quadparts += self.generate_quadrature_loop(rule)
  File "/root/shared/ffcx/ffcx/codegeneration/integral_generator.py", line 273, in generate_quadrature_loop
    tensor_comp, intermediates_fw = self.generate_dofblock_partition(quadrature_rule)
  File "/root/shared/ffcx/ffcx/codegeneration/integral_generator.py", line 387, in generate_dofblock_partition
    block_quadparts, intermediate = self.generate_block_parts(
  File "/root/shared/ffcx/ffcx/codegeneration/integral_generator.py", line 506, in generate_block_parts
    var = fw if isinstance(fw, L.Symbol) else fw.array
AttributeError: 'LiteralFloat' object has no attribute 'array'
```

Issue first reported at
https://fenicsproject.discourse.group/t/asemble-scalar-error-literalfloat-no-array-attribute/14807?u=dokken

**Comment by jorgensd** [comment]
The issue might be: 
https://github.com/FEniCS/ffcx/blob/17045ea9f8c2330bde518976175ceb95b68b7b5d/ffcx/ir/integral.py#L225

**Comment by jorgensd** [comment]
Or it seems like some optimization of zeros is not applied:
```python
import basix.ufl
import ufl

c_el = basix.ufl.element("Lagrange", "triangle", 1, shape=(2,))
mesh = ufl.Mesh(c_el)
C = ufl.as_tensor([[0, 0], [0, 1]])

int = ufl.transpose(C)[0, 0]
# int = C[0, 0]
dx = ufl.Measure("dx", domain=mesh)
J = int * dx

forms = [J]
```
This should be reduced to 0s, but it doesn't seem like it is.

**Comment by jorgensd** [comment]
Even simpler example using `Expression`
```python
import basix.ufl
import ufl

c_el = basix.ufl.element("Lagrange", "interval", 1, shape=(1,))
mesh = ufl.Mesh(c_el)
C = ufl.as_tensor([[0, 0], [0, 1]])

integrand = ufl.transpose(C)[0, 0]
expressions = [(integrand, [[0.1, 0.2]])]
```
returning
```bash
 File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/shared/ffcx/ffcx/__main__.py", line 14, in <module>
    sys.exit(main())
  File "/root/shared/ffcx/ffcx/main.py", line 75, in main
    code_h, code_c = compiler.compile_ufl_objects(
  File "/root/shared/ffcx/ffcx/compiler.py", line 113, in compile_ufl_objects
    ir = compute_ir(analysis, _object_names, _prefix, options, visualise)
  File "/root/shared/ffcx/ffcx/ir/representation.py", line 162, in compute_ir
    ir_expressions = [
  File "/root/shared/ffcx/ffcx/ir/representation.py", line 163, in <listcomp>
    _compute_expression_ir(
  File "/root/shared/ffcx/ffcx/ir/representation.py", line 605, in _compute_expression_ir
    and len(ir["original_constant_offsets"]) == 0
KeyError: 'original_constant_offsets'
```

**Comment by chrisrichardson** [comment]
Is this a problem only because the value is zero. The kernel works with non-zero values in `C[0,0]`?

**Comment by jorgensd** [comment]
Yes, it is only an issue when C[0,0] is 0.

**Comment by michalhabera** [comment]
An optimization won't be applied in this case, that is expected (UFL does not zero parts of expression tree at the granularity of each component).

I think what happens is https://github.com/FEniCS/ffcx/blob/main/ffcx/codegeneration/lnodes.py#L98 triggers and `fw` becomes `LiteralFloat(0.0)` which is neither a temporary symbol nor it has `.array`. A quick fix might be to check for literals and access `.value` in that case. Or in `float_product` return 0.0 for zero literal?

**Comment by chrisrichardson** [comment]
I don't think this will work, as the value 0.0 is still neither a Symbol, nor have an array property, and it will fail in the same place. We could cut out those lines in https://github.com/FEniCS/ffcx/blob/main/ffcx/codegeneration/lnodes.py#L98 - then it will just return `Product()` which will actually multiply by zero.
